[package]
name = "project_1"
description = "First package."
license = "MIT OR Apache-2.0"
repository = "https://github.com/octocat/project-1"
version = "1.0.0"
edition = "2021"
rust-version = "1.56"
publish = ["kellnr"]
